# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
 pipelines:
   - pipeline: 'Result-app'
     source: 'Result-app'
     trigger: true

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '885b573b-8b26-406b-9b3e-ad3a97ec080d'
  imageRepository: 'workerapp'
  containerRegistry: 'myvotingproject.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/worker/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
pool:
 name: 'Agent1'

stages:
- stage: BuildandPushWorkerapp
  displayName: BuildandPushWorkerapp
  jobs:
  - job: BuildandPushWorkerapp
    displayName: BuildandPushWorkerapp
    pool:
      name: 'Agent1'
    steps:
    - task: Docker@2
      displayName: BuildandPushWorkerapp
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
