# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
   - repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'eb538956-e5b6-489c-b083-744bf8c1ac5b'
  imageRepository: 'votingapp'
  containerRegistry: 'myvotingproject.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/vote/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
pool:
 name: 'Agent1'

stages:
- stage: BuildandPushVotingapp
  displayName: BuildandPushVotingapp
  jobs:
  - job: BuildandPushVotingapp
    displayName: BuildandPushVotingapp
    pool:
      name: 'Agent1'
    steps:
    - task: Docker@2
      displayName: BuildandPushVotingapp
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
